### ISSUE TITLE
panic when use tracing_subscriber with tracing_subscriber::fmt::format::Format

### ISSUE THREAD

**Issue by Sherlock-Holo** [tokio-rs/tracing#1365]
## Bug Report

use `tracing_subscriber::fmt::layer().event_format` with `Format::default().json()` will panic

### Version

```
│   │   └── tracing v0.1.25
│   │       ├── tracing-attributes v0.1.15 (proc-macro)
│   │       └── tracing-core v0.1.17
│   ├── tracing v0.1.25 (*)
│   │   └── tracing v0.1.25 (*)
│   ├── tracing v0.1.25 (*)
├── tracing v0.1.25 (*)
├── tracing-opentelemetry v0.11.0
│   ├── tracing v0.1.25 (*)
│   ├── tracing-core v0.1.17 (*)
│   ├── tracing-log v0.1.2
│   │   └── tracing-core v0.1.17 (*)
│   └── tracing-subscriber v0.2.17
│       ├── tracing v0.1.25 (*)
│       ├── tracing-core v0.1.17 (*)
│       ├── tracing-log v0.1.2 (*)
│       └── tracing-serde v0.1.2
│           └── tracing-core v0.1.17 (*)
├── tracing-subscriber v0.2.17 (*)
```

### Platform

Archlinux

### Description

I try this [codes](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d0d2eb4d68b187f169180d4de395ad0d) and cargo run, it panic, the verbose info is

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/rust_learn`
thread 'main' panicked at 'span '123' had malformed fields! this is a bug.
  error: EOF while parsing a value at line 1 column 0
  fields: FormattedFields { fields: "" }', /home/sherlock/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.2.17/src/fmt/format/json.rs:162:49
stack backtrace:
   0: rust_begin_unwind
             at /rustc/6df26f897cffb2d86880544bb451c6b5f8509b2d/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/6df26f897cffb2d86880544bb451c6b5f8509b2d/library/std/src/panicking.rs:435:5
   2: <tracing_subscriber::fmt::format::json::SerializableSpan<Span,N> as serde::ser::Serialize>::serialize
             at /home/sherlock/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.2.17/src/fmt/format/json.rs:162:49
   3: <serde_json::ser::Compound<W,F> as serde::ser::SerializeMap>::serialize_value
             at /home/sherlock/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.64/src/ser.rs:716:22
   4: serde::ser::SerializeMap::serialize_entry
             at /home/sherlock/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.125/src/ser/mod.rs:1823:9
   5: tracing_subscriber::fmt::format::json::<impl tracing_subscriber::fmt::format::FormatEvent<S,N> for tracing_subscriber::fmt::format::Format<tracing_subscriber::fmt::format::json::Json,T>>::format_event::{{closure}}
             at /home/sherlock/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.2.17/src/fmt/format/json.rs:236:21
   6: tracing_subscriber::fmt::format::json::<impl tracing_subscriber::fmt::format::FormatEvent<S,N> for tracing_subscriber::fmt::format::Format<tracing_subscriber::fmt::format::json::Json,T>>::format_event
             at /home/sherlock/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.2.17/src/fmt/format/json.rs:272:9
   7: <tracing_subscriber::fmt::fmt_layer::Layer<S,N,E,W> as tracing_subscriber::layer::Layer<S>>::on_event::{{closure}}
             at /home/sherlock/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.2.17/src/fmt/fmt_layer.rs:742:16
   8: std::thread::local::LocalKey<T>::try_with
             at /home/sherlock/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:376:16
   9: std::thread::local::LocalKey<T>::with
             at /home/sherlock/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:352:9
  10: <tracing_subscriber::fmt::fmt_layer::Layer<S,N,E,W> as tracing_subscriber::layer::Layer<S>>::on_event
             at /home/sherlock/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.2.17/src/fmt/fmt_layer.rs:726:9
  11: <tracing_subscriber::layer::Layered<L,S> as tracing_core::subscriber::Subscriber>::event
             at /home/sherlock/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.2.17/src/layer.rs:651:9
  12: tracing_core::dispatcher::Dispatch::event
             at /home/sherlock/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.17/src/dispatcher.rs:523:9
  13: tracing_core::event::Event::dispatch::{{closure}}
             at /home/sherlock/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.17/src/event.rs:35:13
  14: tracing_core::dispatcher::get_default::{{closure}}
             at /home/sherlock/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.17/src/dispatcher.rs:337:24
  15: std::thread::local::LocalKey<T>::try_with
             at /home/sherlock/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:376:16
  16: tracing_core::dispatcher::get_default
             at /home/sherlock/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.17/src/dispatcher.rs:334:5
  17: tracing_core::event::Event::dispatch
             at /home/sherlock/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.17/src/event.rs:34:9
  18: rust_learn::tracing_ttt::doit
             at ./src/tracing_ttt.rs:17:5
  19: rust_learn::main
             at ./src/main.rs:8:5
  20: core::ops::function::FnOnce::call_once
             at /home/sherlock/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by davidbarsky** [comment]
That's a fun bug, thanks for reporting this! It looks like its coming from https://github.com/tokio-rs/tracing/blob/a75c7b268ccc40b3906a2d0fcda182603fbc299d/tracing-subscriber/src/fmt/format/json.rs#L144. I'm not entirely sure why this is happening, I'm going to dig into this.

**Comment by davidbarsky** [comment]
I'm able to reproduce this, but the panic's happening on https://github.com/tokio-rs/tracing/blob/a75c7b268ccc40b3906a2d0fcda182603fbc299d/tracing-subscriber/src/fmt/format/json.rs#L159.

**Comment by Sherlock-Holo** [comment]
Is there any way to avoid this panic and continue using `Format::default().json()`, I want the log contains file line number and use the json output format, but I read the doc it seems use `Format` is the only way to do it

**Comment by davidbarsky** [comment]
> Is there any way to avoid this panic and continue using Format::default().json(), I want the log contains file line number and use the json output format, but I read the doc it seems use Format is the only way to do it.

Sorry for the delay! There is a workaround, it took me a little bit to realize what was happening. If you create the JSON layer as I do below, your code _will_ run without panicking.

```rust
use tracing_subscriber::fmt::format::{Format, JsonFields};

let layer = tracing_subscriber::fmt::layer()
    .event_format(Format::default().json())
    .fmt_fields(JsonFields::new());
```

The underlying issue that _both_ JSON-specific field _and_ event formatters need to be set. When only `.event_format(Format::default().json())` is set on the layer, `fmt::Layer` defaults to [`DefaultFields`](https://docs.rs/tracing-subscriber/0.2.17/tracing_subscriber/fmt/format/struct.DefaultFields.html instead of [`JsonFields`](https://docs.rs/tracing-subscriber/0.2.17/tracing_subscriber/fmt/format/struct.JsonFields.html). This mismatch causes the confusing panic that you saw.

I'm not sure how to make the state you got into impossible to encounter, as I think it'd require a rethinking of how we handle emitting JSON in `tracing-subscriber`—this sort of issue might merit us creating a new JSON-specific subscriber. That being said, this can documented a bit better.

**Comment by malobre** [comment]
FYI, the `Pretty`  formatter checks if fields are empty before printing:
https://github.com/tokio-rs/tracing/blob/9ac27fbc92b1763f5d533e684d33eebe48652a58/tracing-subscriber/src/fmt/format/pretty.rs#L209-L214

The `Json` formatter does not:
https://github.com/tokio-rs/tracing/blob/9ac27fbc92b1763f5d533e684d33eebe48652a58/tracing-subscriber/src/fmt/format/json.rs#L131-L140

I believe this would fix this bug. Also the TODO seems to be outdated.

**Comment by dsxmachina** [comment]
I ran into the same Issue without using layers; 
The thing that confuses me - when reading the docs it seems that I only have to change ".compact()" or ".pretty()" to ".json()".
Maybe your fix could be added to the documentation to avoid anyone else running into this ?
However, your fix in my code (which is essentially the example from the docs):
```
    let format = fmt::format()
        .with_timer(UtcTime::new(format_description!(
            "[hour]:[minute]:[second].[subsecond digits:6]"
        )))
        .with_level(true)
        .with_target(false)
        .with_thread_ids(false)
        .with_thread_names(false)
        .json();
    tracing_subscriber::fmt()
        .event_format(format)
        .fmt_fields(JsonFields::new())
        .init();
```
