### ISSUE TITLE
set_default from within get_default panics with `already borrowed: BorrowMutError`

### ISSUE THREAD

**Issue by lilyball** [tokio-rs/tracing#1655]
### Version

```
asdf-tracing v0.1.0 (/Users/lily/Dev/Scratch/asdf-tracing)
├── tracing v0.1.29
│   ├── tracing-attributes v0.1.18 (proc-macro)
│   └── tracing-core v0.1.21
└── tracing-subscriber v0.2.25
    ├── tracing v0.1.29 (*)
    ├── tracing-core v0.1.21 (*)
    ├── tracing-log v0.1.2
    │   └── tracing-core v0.1.21 (*)
    └── tracing-serde v0.1.2
        └── tracing-core v0.1.21 (*)
```

### Platform

Darwin DeerBook 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

### Crates

tracing-core

### Description

`tracing_core::dispatcher::get_default()` documents that calling it from within itself will get `Dispatch::none`. It does not document any interaction with `set_default()`. And `tracing_core::dispatcher::set_default()` documents no interaction with `get_default()`.

Despite this, calling `set_default()` from within `get_default()` panics with `already borrowed: BorrowMutError`, which appears to be entirely unintentional. It actually does have logic in `set_default()` to declare "the state can be entered", which suggests the desire for `set_default()` to allow recursive dispatch. And this makes sense too, if I want to log debug events from within my subscriber I may want to be able to temporarily swap to a debug dispatch, log the events, and back out again. Though even without the panic, that wouldn't work right today as the `DefaultGuard` wouldn't reset the `can_enter` state (and also, what happens if you set the already-entered dispatch as default and tried to re-enter it?)

At a minimum, this incompatibility should be documented, and ideally the panic message replaced with a more meaningful one that identifies the problem. Ideally this would be fixed at a more general level though.

### Proposal

The panic here is because the default is stored as a `RefCell`. `get_default()` borrows this (actually, borrows it mutably, but the `can_enter` state avoids nested `get_default` calls from panicking), and `set_default()` calls `replace()` on it, which will panic if it's already borrowed. More generally, the problem is we're calling external code (the closure argument) with the borrow held.

One possible solution here is to store the `dispatch` as a `RefCell<Rc<Dispatch>>`. This way we can borrow it, clone the `Rc`, and drop the borrow, all prior to calling the user function. `set_default` would just wrap the `Dispatch` in an `Rc` before replacing it. Because this is all thread-local, the use of the `Rc` is fine and quite cheap.

This would allow code like

```rust
impl Subscriber for MySubscriber {
    fn enter(&self, span: &Id) {
        let _guard = set_default(self.debug_subscriber);
        let _span = trace_span!("enter", self, span).entered();
        // do work here that potentially involves trace events
    }
}
```

and more generally would make it safe to use `set_default()` and `with_default()` from library code without worrying about the call stack.

#### Alternatives

We could make `set_default()` do nothing at all if called from within `get_default()`, but that's rather surprising, especially if the `DefaultGuard` is returned up the stack past the `get_default()`.

We could change the code to just `clone()` the `Dispatch`, allowing us to release the borrow immediately before calling the closure. This feels like an unnecessary expense to do on every log call though.

### Additional considerations

Once this panic is fixed, we can write code like

```rust
get_default(|dispatch| {
    let _guard = set_default(dispatch);
    get_default(|dispatch| {
        // hey this gets us the working dispatch!
    });
});
```

This is a bit weird, and could be abused to recursively log events. This is probably okay though, as it's rather hard to do by accident. It looks like the ban on recursive `get_dispatch` is just to prevent accidental infinite recursion if the various `Subscriber` methods try to log trace events.

**Comment by lilyball** [comment]
Having said that, I'm not sure if it's actually a good thing for `let _guard = get_default(|_| set_default(foo)); info!(…)` to not be able to log using the `set_default`. Which is to say, that looks like it should behave like `let _guard = set_default(get_default(|_| foo)); info!(…)`. And this style could be used if I want to wrap the current dispatch in something temporarily.

**Comment by Igosuki** [comment]
Hi, I observe the same error when using tokio/console :

```
thread 'main' panicked at 'already borrowed: BorrowMutError', /home/geps/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.21/src/dispatcher.rs:688:31
stack backtrace:
   0: rust_begin_unwind
             at /rustc/efec545293b9263be9edfb283a7aa66350b3acbf/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/efec545293b9263be9edfb283a7aa66350b3acbf/library/core/src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at /rustc/efec545293b9263be9edfb283a7aa66350b3acbf/library/core/src/result.rs:1660:5
   3: tracing_core::dispatcher::set_default
   4: <console_subscriber::ConsoleLayer as tracing_subscriber::layer::Layer<S>>::on_enter
   5: <tracing_subscriber::layer::layered::Layered<L,S> as tracing_core::subscriber::Subscriber>::enter
   6: tracing::span::Span::in_scope
   7: <tokio::sync::mutex::Mutex<T> as core::fmt::Debug>::fmt
...
  24: <&mut W as core::fmt::Write>::write_fmt
  25: <tracing_subscriber::fmt::format::Writer as core::fmt::Write>::write_fmt
  26: <tracing_subscriber::fmt::format::DefaultVisitor as tracing_core::field::Visit>::record_debug
  27: <tracing_subscriber::fmt::format::Format<tracing_subscriber::fmt::format::Full,T> as tracing_subscriber::fmt::format::FormatEvent<S,N>>::format_event
  28: std::thread::local::LocalKey<T>::with
  29: <tracing_subscriber::layer::layered::Layered<L,S> as tracing_core::subscriber::Subscriber>::event
  30: tracing_log::dispatch_record::{{closure}}
  31: tracing_core::dispatcher::get_default
  32: <tracing_log::log_tracer::LogTracer as log::Log>::log
```
