### ISSUE TITLE
tracing-subscriber panic when using tracing-appender with tracing-tree

### ISSUE THREAD

**Issue by joxcat** [tokio-rs/tracing#2112]
### Version

```
tracing-tree-appender v0.1.0 (/user_home/data/tracing-tree-appender)
├── tracing v0.1.34
│   ├── tracing-attributes v0.1.21 (proc-macro)
│   └── tracing-core v0.1.26
├── tracing-appender v0.2.2
│   └── tracing-subscriber v0.3.11
│       ├── tracing-core v0.1.26 (*)
│       └── tracing-log v0.1.3
│           └── tracing-core v0.1.26 (*)
├── tracing-subscriber v0.3.11 (*)
└── tracing-tree v0.2.0 (https://github.com/joxcat/tracing-tree.git#f8ee34ce)
    ├── tracing-core v0.1.26 (*)
    ├── tracing-log v0.1.3 (*)
    └── tracing-subscriber v0.3.11 (*)
```

### Platform

```
Linux 41899c668183 4.19.0-17-amd64 #1 SMP Debian 4.19.194-2 (2021-06-21) x86_64 GNU/Linux
```

### Description

I wanted to follow the [`fmt-multiple-writer.rs`](https://github.com/tokio-rs/tracing/blob/tracing-subscriber-0.3.11/examples/examples/fmt-multiple-writers.rs) example and use [`tracing-tree`](https://github.com/davidbarsky/tracing-tree) to format the output.

For the context, [`tracing-tree`](https://github.com/davidbarsky/tracing-tree) have an issue where `HierarchicalLayer` require a `Suscriber: Debug` bound [tracing-tree#45](https://github.com/davidbarsky/tracing-tree/issues/45). So I forked the repo and naively tried to remove the `Subscriber: Debug` bound (here: [joxcat/tracing-tree](https://github.com/joxcat/tracing-tree)), all the repos units tests are passing.

My problem is that if I try to use it like in the minimal example here https://github.com/joxcat/tracing-tree-appender it panic when I try to use a span with one `HierarchicalLayer` which write to stdout and one `HierarchicalLayer` which write to a log file.

I posted the issue here because the backtrace rewind to a panic in `tracing-subscriber`, but I'm not sure if it belongs more to this repository or to `tracing-tree`, please redirect me if it's not the good place.

Here is the full stacktrace:

```shell
$ RUST_BACKTRACE=full cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/tracing-tree-appender`
main 
thread 'main' panicked at 'assertion failed: self.replace(val).is_none()', /user_home/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.3.11/src/registry/extensions.rs:88:9
stack backtrace:
   0:     0x55ab0554f44d - std::backtrace_rs::backtrace::libunwind::trace::hee598835bc88d35b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55ab0554f44d - std::backtrace_rs::backtrace::trace_unsynchronized::h9cdc730ba5cf5d72
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55ab0554f44d - std::sys_common::backtrace::_print_fmt::h75aeaf7ed30e43fa
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55ab0554f44d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h606862f787600875
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55ab05570afc - core::fmt::write::he803f0f418caf762
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
   5:     0x55ab0554be78 - std::io::Write::write_fmt::h70bc45872f37e7bb
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
   6:     0x55ab05551537 - std::sys_common::backtrace::_print::h64d038cf8ac3e13e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55ab05551537 - std::sys_common::backtrace::print::h359300b4a7fccf65
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55ab05551537 - std::panicking::default_hook::{{closure}}::hf51be35e2f510149
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
   9:     0x55ab05551200 - std::panicking::default_hook::h03ca0f22e1d2d25e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
  10:     0x55ab05551c89 - std::panicking::rust_panic_with_hook::h3b7380e99b825b63
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:698:17
  11:     0x55ab05551939 - std::panicking::begin_panic_handler::{{closure}}::h8e849d0710154ce0
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:586:13
  12:     0x55ab0554f914 - std::sys_common::backtrace::__rust_end_short_backtrace::hedcdaddbd4c46cc5
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55ab05551689 - rust_begin_unwind
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
  14:     0x55ab05496433 - core::panicking::panic_fmt::he1bbc7336d49a357
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
  15:     0x55ab054962fd - core::panicking::panic::h4241c5ccea17faca
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:48:5
  16:     0x55ab0549d73a - tracing_subscriber::registry::extensions::ExtensionsMut::insert::hfd82348378b0be75
                               at /user_home/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.3.11/src/registry/extensions.rs:88:9
  17:     0x55ab054aa810 - <tracing_tree::HierarchicalLayer<W> as tracing_subscriber::layer::Layer<S>>::on_new_span::h98e2081f91b31d35
                               at /user_home/.cargo/git/checkouts/tracing-tree-4316a33051f33da2/f8ee34c/src/lib.rs:286:9
  18:     0x55ab054a1793 - <tracing_subscriber::layer::layered::Layered<L,S> as tracing_core::subscriber::Subscriber>::new_span::h9b9d27570428d64d
                               at /user_home/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.3.11/src/layer/layered.rs:100:9
  19:     0x55ab0552d875 - <alloc::sync::Arc<dyn tracing_core::subscriber::Subscriber+core::marker::Send+core::marker::Sync> as tracing_core::subscriber::Subscriber>::new_span::h7688a032f8e37863
                               at /user_home/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.26/src/subscriber.rs:693:9
  20:     0x55ab0552ca83 - tracing_core::dispatcher::Dispatch::new_span::h3574eaee42883609
                               at /user_home/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.26/src/dispatcher.rs:465:9
  21:     0x55ab0552c32d - tracing::span::Span::make_with::h25cb4e8407625f1d
                               at /user_home/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.34/src/span.rs:569:18
  22:     0x55ab0552c2d2 - tracing::span::Span::new_with::h7724a9fbf449ba73
                               at /user_home/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.34/src/span.rs:448:9
  23:     0x55ab0552c24d - tracing::span::Span::new::{{closure}}::h19f15ab6f65380bd
                               at /user_home/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.34/src/span.rs:437:44
  24:     0x55ab0552c8cc - tracing_core::dispatcher::get_default::{{closure}}::hb70279b6f8614e82
                               at /user_home/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.26/src/dispatcher.rs:331:24
  25:     0x55ab0552d22d - std::thread::local::LocalKey<T>::try_with::hc72976cb584fa158
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:413:16
  26:     0x55ab0552c50b - tracing_core::dispatcher::get_default::hf0acdcdb56612645
                               at /user_home/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.26/src/dispatcher.rs:328:5
  27:     0x55ab0552c209 - tracing::span::Span::new::h7e7cf47fcc79f6b7
                               at /user_home/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.34/src/span.rs:437:9
  28:     0x55ab054992f9 - tracing_tree_appender::main::h8a6f080691d33abc
                               at /user_home/data/tracing-tree-appender/src/main.rs:16:5
  29:     0x55ab0549e31b - core::ops::function::FnOnce::call_once::ha2f95afae3d9d88f
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
  30:     0x55ab0549acae - std::sys_common::backtrace::__rust_begin_short_backtrace::h5474b339f010a01b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:122:18
  31:     0x55ab054a07d1 - std::rt::lang_start::{{closure}}::h4bf0cab472d1cce9
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:145:18
  32:     0x55ab0554eb31 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb7014f43484a8b4e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:259:13
  33:     0x55ab0554eb31 - std::panicking::try::do_call::h7bc9dc436daeb8c7
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  34:     0x55ab0554eb31 - std::panicking::try::h653d68a27ff5f175
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  35:     0x55ab0554eb31 - std::panic::catch_unwind::h9d739f9f59895e68
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  36:     0x55ab0554eb31 - std::rt::lang_start_internal::{{closure}}::hf006f2bc7ce22bbe
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:48
  37:     0x55ab0554eb31 - std::panicking::try::do_call::hfb39d6df61a2e69f
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  38:     0x55ab0554eb31 - std::panicking::try::h13e2d225134958ac
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  39:     0x55ab0554eb31 - std::panic::catch_unwind::h3bd49b5a5dfb1a50
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  40:     0x55ab0554eb31 - std::rt::lang_start_internal::h2ba92edce36c035e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:20
  41:     0x55ab054a07a0 - std::rt::lang_start::h416c864450f4e664
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:144:17
  42:     0x55ab054993ec - main
  43:     0x7fb06f373d0a - __libc_start_main
  44:     0x55ab05496cba - _start
  45:                0x0 - <unknown>
```

**Comment by hawkw** [comment]
This appears to be a bug in `tracing-tree`; it's using the `ExtensionsMut::insert` method [here](https://github.com/davidbarsky/tracing-tree/blob/c577326deec991832cbe4adee9254f073d9432b3/src/lib.rs#L286), which panics when an extension already exists for a given span. This is [documented behavior](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/registry/struct.ExtensionsMut.html#method.insert) of that method rather than a bug in `tracing-subscriber`. 

The `tracing-tree` crate should probably either use [`ExtensionsMut::replace`](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/registry/struct.ExtensionsMut.html#method.replace) which overwrites any previous value, or (preferably, as it's more efficient) check if an extension of type `tracing_tree::Data` already exists before inserting it, to avoid constructing the extension twice.

cc @davidbarsky

**Comment by davidbarsky** [comment]
Yup, this is a bug in tracing-tree. sorry about that.

**Comment by davidbarsky** [comment]
Closed by https://github.com/davidbarsky/tracing-tree/pull/46.
