### ISSUE TITLE
Tried to drop a ref to Id(3), but no such span exists!

### ISSUE THREAD

**Issue by scw00** [tokio-rs/tracing#2870]
## Bug Report

tried to drop a ref to Id(3), but no such span exists!

### Version

tracing-core-0.1.32
tracing-subscriber-0.3.18

### Platform

linux

### Crates

tracing-subscriber or tracing-core

### Description

I created a span  S from a dispatcher A. And the Span::inner has recorded the dispatcher A. Then I spawn a future with_dispatch(B). The dispatcher B replace the global dispatcher A with Kind::Scope. 

After that, The spawned  future is correctly entered the span S, but panicked on dropping because the tracing-subscriber is can't find the span's id from local (Kind::Scope) dispatcher B , Which is existed in dispatchter A.

**Comment by rklaehn** [comment]
I am seeing this as well. I got a pretty complex program ( https://github.com/n0-computer/iroh ) where I am hunting for an unexpected panic, and I am seeing multiple things like this in the logs:

```
thread 'test_sync_via_relay' panicked at /Users/rklaehn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.18/src/registry/sharded.rs:350:21:
tried to drop a ref to Id(11260098580054061), but no such span exists!
```

If the ids are assigned consecutively, this seems like a very high number, indicating some kind of memory corruption. If they are assigned randomly, this would be not out of the usual...

**Comment by mladedav** [comment]
@rklaehn unless you're using multiple different subscribers/dispatchers, your problem will be different to the original one.

Can you open a new issue please so we can keep it separate?

**Comment by interj** [comment]
Hi, I believe I have reproduced the issue here: https://github.com/interj/tracing_test/blob/main/src/main.rs

Creating new subscribers in different threads/tasks seems to not work with previously defined spans.

**Comment by dzmitry-lahoda** [comment]
I got panic when I used same runtime and dispatcher::set_default. As dispatcher per thread, not per task, tokio reused thread else where and range ids in different dispatchers did not matched.

**Comment by JakeDern** [comment]
I am having an identical issue to what @rklaehn was seeing. I have a list of closures that return a future to run on another thread and I see the same failed to drop message with a suspiciously large Id. This happens when trying to attach a subscriber to the future so that I can track all the events from each function individually before running it in a task:

```rust
for f in suite.funcs.iter() {
    let sub = tracing_subscriber::fmt()
        .with_max_level(Level::TRACE)
        .with_target(false)
        .finish();

    let sub = Arc::new(sub);
    sub.clone().set_default();

    let fut = (test.test_func)().with_subscriber(sub.clone());
    let handle = tokio::task::spawn(fut);
}

```

Stack trace:

```
tried to drop a ref to Id(274877906946), but no such span exists!
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4d04a1c9360c09fce5a777a8668a06a30b7cb4df/library/std/src/panicking.rs:692:5
   1: core::panicking::panic_fmt
             at /rustc/4d04a1c9360c09fce5a777a8668a06a30b7cb4df/library/core/src/panicking.rs:75:14
   2: <tracing_subscriber::registry::sharded::Registry as tracing_core::subscriber::Subscriber>::try_close
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tracing-subscriber-0.3.19/src/registry/sharded.rs:350:21
   3: <tracing_subscriber::layer::layered::Layered<L,S> as tracing_core::subscriber::Subscriber>::try_close
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tracing-subscriber-0.3.19/src/layer/layered.rs:186:12
   4: <tracing_subscriber::layer::layered::Layered<L,S> as tracing_core::subscriber::Subscriber>::try_close
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tracing-subscriber-0.3.19/src/layer/layered.rs:186:12
   5: <tracing_subscriber::fmt::Subscriber<N,E,F,W> as tracing_core::subscriber::Subscriber>::try_close
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tracing-subscriber-0.3.19/src/fmt/mod.rs:434:9
   6: tracing_core::dispatcher::Dispatch::try_close
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tracing-core-0.1.33/src/dispatcher.rs:703:9
   7: <tracing_subscriber::registry::sharded::Registry as tracing_core::subscriber::Subscriber>::exit::{{closure}}
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tracing-subscriber-0.3.19/src/registry/sharded.rs:303:52
   8: tracing_core::dispatcher::get_default
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tracing-core-0.1.33/src/dispatcher.rs:389:16
   9: <tracing_subscriber::registry::sharded::Registry as tracing_core::subscriber::Subscriber>::exit
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tracing-subscriber-0.3.19/src/registry/sharded.rs:303:17
  10: <tracing_subscriber::layer::layered::Layered<L,S> as tracing_core::subscriber::Subscriber>::exit
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tracing-subscriber-0.3.19/src/layer/layered.rs:162:9
  11: <tracing_subscriber::layer::layered::Layered<L,S> as tracing_core::subscriber::Subscriber>::exit
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tracing-subscriber-0.3.19/src/layer/layered.rs:162:9
  12: <tracing_subscriber::fmt::Subscriber<N,E,F,W> as tracing_core::subscriber::Subscriber>::exit
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tracing-subscriber-0.3.19/src/fmt/mod.rs:419:9
  13: <alloc::sync::Arc<S> as tracing_core::subscriber::Subscriber>::exit
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tracing-core-0.1.33/src/subscriber.rs:846:9
  14: tracing_core::dispatcher::Dispatch::exit
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tracing-core-0.1.33/src/dispatcher.rs:636:9
  15: tracing::span::Span::do_exit
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tracing-0.1.41/src/span.rs:1054:13
  16: <tracing::span::Entered as core::ops::drop::Drop>::drop
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tracing-0.1.41/src/span.rs:1562:9
  17: core::ptr::drop_in_place<tracing::span::Entered>
             at /home/jakedern/.msrustup/packages/rust.tools-x86_64-unknown-linux-gnu.1.85.0-ms-20250228.3/tools/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:523:1
  18: <hyper_util::client::legacy::connect::dns::GaiResolver as tower_service::Service<hyper_util::client::legacy::connect::dns::Name>>::call::{{closure}}
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/hyper-util-0.1.10/src/client/legacy/connect/dns.rs:127:9
  19: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tokio-1.43.0/src/runtime/blocking/task.rs:42:21
  20: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tokio-1.43.0/src/runtime/task/core.rs:331:17
  21: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tokio-1.43.0/src/loom/std/unsafe_cell.rs:16:9
  22: tokio::runtime::task::core::Core<T,S>::poll
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tokio-1.43.0/src/runtime/task/core.rs:320:13
  23: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tokio-1.43.0/src/runtime/task/harness.rs:532:19
  24: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/jakedern/.msrustup/packages/rust.tools-x86_64-unknown-linux-gnu.1.85.0-ms-20250228.3/tools/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
  25: std::panicking::try::do_call
             at /home/jakedern/.msrustup/packages/rust.tools-x86_64-unknown-linux-gnu.1.85.0-ms-20250228.3/tools/lib/rustlib/src/rust/library/std/src/panicking.rs:584:40
  26: __rust_try
  27: std::panicking::try
             at /home/jakedern/.msrustup/packages/rust.tools-x86_64-unknown-linux-gnu.1.85.0-ms-20250228.3/tools/lib/rustlib/src/rust/library/std/src/panicking.rs:547:19
  28: std::panic::catch_unwind
             at /home/jakedern/.msrustup/packages/rust.tools-x86_64-unknown-linux-gnu.1.85.0-ms-20250228.3/tools/lib/rustlib/src/rust/library/std/src/panic.rs:358:14
  29: tokio::runtime::task::harness::poll_future
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tokio-1.43.0/src/runtime/task/harness.rs:520:18
  30: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tokio-1.43.0/src/runtime/task/harness.rs:209:27
  31: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tokio-1.43.0/src/runtime/task/harness.rs:154:15
  32: tokio::runtime::task::raw::poll
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tokio-1.43.0/src/runtime/task/raw.rs:271:5
  33: tokio::runtime::task::raw::RawTask::poll
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tokio-1.43.0/src/runtime/task/raw.rs:201:18
  34: tokio::runtime::task::UnownedTask<S>::run
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tokio-1.43.0/src/runtime/task/mod.rs:486:9
  35: tokio::runtime::blocking::pool::Task::run
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tokio-1.43.0/src/runtime/blocking/pool.rs:161:9
  36: tokio::runtime::blocking::pool::Inner::run
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tokio-1.43.0/src/runtime/blocking/pool.rs:511:17
  37: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/jakedern/.cargo/registry/src/msdata.pkgs.visualstudio.com-e4a26dfce049b0a8/tokio-1.43.0/src/runtime/blocking/pool.rs:469:13

```

**Comment by svix-jplatte** [comment]
I can still reproduce with tracing-subscriber 0.3.21 / tracing-core 0.1.35 / tracing 0.1.42, unfortunately.

**Comment by svix-jbrown** [comment]
Still happening in 2026; any more debugging information we can provide?

**Comment by dzmitry-lahoda** [comment]
Nice candidate to root cause and produce tests via AI (and draft variants of fixes may be), but https://github.com/tokio-rs/tracing/blob/main/CONTRIBUTING.md does not mention AI contributing guidelines
