### ISSUE TITLE
panicked at 'already borrowed: BorrowMutError'

### ISSUE THREAD

**Issue by d-e-s-o** [tokio-rs/tracing#521]
### Version

tokio-0.2.8
tracing-0.1.11
tracing-futures-0.2.0
tracing-subscriber-0.1.6

### Platform

Linux 4.19, 64 bit

### Description

Here is a backtrace of a panic that I am seeing:
```
thread 'XXX' panicked at 'already borrowed: BorrowMutError', src/libcore/result.rs:1165:5
stack backtrace:
   0:     0x562795ace824 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h49f360c38f8651b5
   1:     0x562795ae536d - core::fmt::write::h0a4f9eb1997ae8a7
   2:     0x562795acc785 - std::io::Write::write_fmt::h7dddb1e6ae92c397
   3:     0x562795ab897e - std::panicking::default_hook::{{closure}}::h650b8529407fbfb9
   4:     0x562795ab8690 - std::panicking::default_hook::hdeafb3553c3034bb
   5:     0x562795ab907b - std::panicking::rust_panic_with_hook::hb1d00334cc769e24
   6:     0x562795ab8c1e - std::panicking::continue_panic_fmt::h9ffc67cd1203406a
   7:     0x562795ab8b06 - rust_begin_unwind
   8:     0x562795ae9b3e - core::panicking::panic_fmt::h86f58df9a8c5a71a
   9:     0x562795ae48e7 - core::result::unwrap_failed::h373a200fe2c63f59
  10:     0x5627956d7cfb - core::result::Result<T,E>::expect::h77a58c96b4bcf4e3
                               at rustc-1.40.0-src/src/libcore/result.rs:960
  11:     0x5627956d92bd - core::cell::RefCell<T>::borrow_mut::h564a37b947462532
                               at rustc-1.40.0-src/src/libcore/cell.rs:869
  12:     0x562795375391 - tracing_core::dispatcher::get_default::{{closure}}::h1f37d5722391ab26
                               at tracing-core-0.1.8/src/dispatcher.rs:324
  13:     0x56279537cb16 - std::thread::local::LocalKey<T>::try_with::h18e5842f0027c606
                               at rustc-1.40.0-src/src/libstd/thread/local.rs:262
  14:     0x5627953752a8 - tracing_core::dispatcher::get_default::h3b40ce86dec3885e
                               at tracing-core-0.1.8/src/dispatcher.rs:319
  15:     0x56279532710a - <tracing_subscriber::fmt::span::Data as core::ops::drop::Drop>::drop::h52eea92f7d71f65f
                               at tracing-subscriber-0.1.6/src/fmt/span.rs:474
  16:     0x5627953178af - core::ptr::real_drop_in_place::hb254547c94374ab4
                               at rustc-1.40.0-src/src/libcore/ptr/mod.rs:175
  17:     0x562795314d43 - core::ptr::real_drop_in_place::h0d34c0de682e2dff
                               at rustc-1.40.0-src/src/libcore/ptr/mod.rs:175
  18:     0x562795314c7a - core::ptr::real_drop_in_place::h0a0347e9be60415a
                               at rustc-1.40.0-src/src/libcore/ptr/mod.rs:175
  19:     0x562795318981 - core::ptr::real_drop_in_place::hf407b511a044ab48
                               at rustc-1.40.0-src/src/libcore/ptr/mod.rs:175
  20:     0x5627953161ec - core::ptr::real_drop_in_place::h58bf6ffe849e3654
                               at rustc-1.40.0-src/src/libcore/ptr/mod.rs:175
  21:     0x562795317e86 - core::ptr::real_drop_in_place::hcbb0dca299f2213f
                               at rustc-1.40.0-src/src/libcore/ptr/mod.rs:175
  22:     0x5627953309b2 - core::ptr::drop_in_place::hef12ca4e70bba5c1
                               at rustc-1.40.0-src/src/libcore/ptr/mod.rs:165
  23:     0x5627953309b2 - <alloc::vec::Vec<T> as core::ops::drop::Drop>::drop::h1453205d377e193d
                               at rustc-1.40.0-src/src/liballoc/vec.rs:2302
  24:     0x562795316e45 - core::ptr::real_drop_in_place::h871fefef96c4b52e
                               at rustc-1.40.0-src/src/libcore/ptr/mod.rs:175
  25:     0x562795318a91 - core::ptr::real_drop_in_place::hf6ca1e76b9e6552c
                               at rustc-1.40.0-src/src/libcore/ptr/mod.rs:175
  26:     0x562795318741 - core::ptr::real_drop_in_place::he8df54ebe8996814
                               at rustc-1.40.0-src/src/libcore/ptr/mod.rs:175
  27:     0x5627953151dc - core::ptr::real_drop_in_place::h1bd854f9ca66995d
                               at rustc-1.40.0-src/src/libcore/ptr/mod.rs:175
  28:     0x5627953156b1 - core::ptr::real_drop_in_place::h2d89113cb53dd484
                               at rustc-1.40.0-src/src/libcore/ptr/mod.rs:175
  29:     0x562795314f81 - core::ptr::real_drop_in_place::h11a894d2a4e26c6b
                               at rustc-1.40.0-src/src/libcore/ptr/mod.rs:175
  30:     0x562795317c8a - core::ptr::real_drop_in_place::hc5a8ac7984880bec
                               at rustc-1.40.0-src/src/libcore/ptr/mod.rs:175
  31:     0x562795316aa1 - core::ptr::real_drop_in_place::h796fd9c3394d2eeb
                               at rustc-1.40.0-src/src/libcore/ptr/mod.rs:175
  32:     0x5627956cf32a - core::ptr::real_drop_in_place::hf2b71870c152cbd5
                               at rustc-1.40.0-src/src/libcore/ptr/mod.rs:175
  33:     0x5627956cd697 - core::ptr::drop_in_place::hb23c9a139f76b72a
                               at rustc-1.40.0-src/src/libcore/ptr/mod.rs:165
  34:     0x5627956cd697 - alloc::sync::Arc<T>::drop_slow::h1f0da8c4bc8139df
                               at rustc-1.40.0-src/src/liballoc/sync.rs:706
  35:     0x5627956cdd2e - <alloc::sync::Arc<T> as core::ops::drop::Drop>::drop::h5211c5c2cb880125
                               at rustc-1.40.0-src/src/liballoc/sync.rs:1234
  36:     0x56279511b39f - core::ptr::real_drop_in_place::h8b1be4a7240e005f
                               at rustc-1.40.0-src/src/libcore/ptr/mod.rs:175
  37:     0x562795127c4e - core::ptr::real_drop_in_place::he732a18cc14681e5
                               at rustc-1.40.0-src/src/libcore/ptr/mod.rs:175
  38:     0x562794f8394e - <tracing_core::dispatcher::DefaultGuard as core::ops::drop::Drop>::drop::{{closure}}::hbfa5a874f1845e3c
                               at tracing-core-0.1.8/src/dispatcher.rs:679
  39:     0x5627950588b5 - std::thread::local::LocalKey<T>::try_with::hc8d7f42af0a4bce7
                               at rustc-1.40.0-src/src/libstd/thread/local.rs:262
  40:     0x562794ffb585 - <tracing_core::dispatcher::DefaultGuard as core::ops::drop::Drop>::drop::h21c832140f85bb16
                               at tracing-core-0.1.8/src/dispatcher.rs:678
  41:     0x5627951261f1 - core::ptr::real_drop_in_place::hd937d2b4f9846ba8
                               at rustc-1.40.0-src/src/libcore/ptr/mod.rs:175
  42:     0x56279520e15c - XXX::{{closure}}::h1e4de1c9907e26ce
                               at mysrc.rs:535
  43:     0x5627952fc72b - <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}::hca856526bd83a235
                               at rustc-1.40.0-src/src/libstd/future.rs:43
  44:     0x5627952e13db - std::future::set_task_context::h2a30daad117a5637
                               at rustc-1.40.0-src/src/libstd/future.rs:79
  45:     0x5627952f1f8a - <std::future::GenFuture<T> as core::future::future::Future>::poll::hd58f53522e574ba6
                               at rustc-1.40.0-src/src/libstd/future.rs:43
  46:     0x562794fb969f - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::h1f4d9fa50ed2f080
                               at tokio-0.2.8/src/runtime/basic_scheduler.rs:138
  47:     0x56279530b946 - tokio::runtime::Runtime::block_on::{{closure}}::hbb5eb6c1cc5805f1
                               at tokio-0.2.8/src/runtime/mod.rs:411
  48:     0x56279506d644 - tokio::runtime::context::enter::hd04ae22d2d88afdb
                               at tokio-0.2.8/src/runtime/context.rs:72
  49:     0x5627952bdea2 - tokio::runtime::handle::Handle::enter::h560767324c1194ba
                               at tokio-0.2.8/src/runtime/handle.rs:33
  50:     0x562795309cd4 - tokio::runtime::Runtime::block_on::h024553f90fa46770
                               at tokio-0.2.8/src/runtime/mod.rs:408
  51:     0x56279516d9e1 - XXX::h9297e2d4fa385a2e
                               at mysrc.rs:535
  52:     0x56279520de82 - XXX::{{closure}}::he181366d4ed0ed89
                               at mysrc.rs:535
  53:     0x56279510611e - core::ops::function::FnOnce::call_once::h729773d4217bad4a
                               at rustc-1.40.0-src/src/libcore/ops/function.rs:227
  54:     0x562795671bcf - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::he5a8d75d1740b7bc
  55:     0x562795ad137a - __rust_maybe_catch_panic
  56:     0x562795660999 - test::run_test_in_process::h814745e7e55afc2d
  57:     0x56279567ba74 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf4c6d5087a458417
  58:     0x56279567a136 - std::panicking::try::do_call::h6b0c59c7095d8c59
  59:     0x562795ad137a - __rust_maybe_catch_panic
  60:     0x56279567c396 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h301f285fb35562ea
  61:     0x562795ace56f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hc3b2433baa9cfd99
  62:     0x562795ab8080 - std::sys_common::thread::start_thread::ha6f30be11f69baf4
  63:     0x562795acd9e6 - std::sys::unix::thread::Thread::new::thread_start::he1a163e69060097c
  64:     0x7fb0d143c3a7 - start_thread
                               at glibc-2.29-r7/work/glibc-2.29/nptl/pthread_create.c:486
  65:     0x7fb0d134eaff - __clone
  66:                0x0 - <unknown>
```

I am "experimenting" with `tracing`. My understanding of what is happening is that I am using `tracing::subscriber::set_default` and `tracing-core`, in some shut down path, is dropping the dispatcher, accessing some state in the process and panicking on a `RefCell`.
If I remove my call to `tracing::subscriber::set_default` there is no panic.

Unfortunately while I can reproduce the issue, I can't share all the details and I have not been able to reproduce it in a more minimalistic setting.

Suffice to say that that the following (clunky) patch fixes the issue for me:
```diff
--- tracing-core/src/dispatcher.rs
+++ tracing-core/src/dispatcher.rs
@@ -315,15 +321,20 @@
             if state.can_enter.replace(false) {
                 let _guard = Entered(&state.can_enter);

-                let mut default = state.default.borrow_mut();
+                let result = state.default.try_borrow_mut();

-                if default.is::<NoSubscriber>() {
-                    if let Some(global) = get_global() {
-                        // don't redo this call on the next check
-                        *default = global.clone();
+                match result {
+                  Ok(mut default) => {
+                    if default.is::<NoSubscriber>() {
+                        if let Some(global) = get_global() {
+                            // don't redo this call on the next check
+                            *default = global.clone();
+                        }
                     }
+                    f(&*default)
+                  },
+                  Err(..) => f(&Dispatch::none()),
                 }
-                f(&*default)
             } else {
                 f(&Dispatch::none())
             }

```
(in English, I am just replacing a `borrow_mut` with `try_borrow_mut`. The question is whether the call to `f(&Dispatch::none())` is fine in this context or not)

It would be great if someone more familiar with the `tracing` code base could take a look. Irrespective of what I am doing, this panic does not seem right.

**Comment by hawkw** [comment]
Ahh, this is interesting: it looks like the issue is that the code in `tracing-subscriber`'s `Registry` that tries to get the default dispatcher to drop a span's parent will cause this panic if it runs _while_ the subscriber is being dropped.

While the change to `try_borrow_mut` should fix this, I am not totally sure if it is the best solution. The `RefCell` _should_ never be borrowed mutably in two places at once, and if that happens it's a bug in `tracing`. Rather than silently nop-ing in that case, I think we might want to change the code for unsetting the default dispatcher a bit. 

Here, where we unset the current default dispatcher:
https://github.com/tokio-rs/tracing/blob/d0b22bb331d3c44df2326b2739998948d056f6d4/tracing-core/src/dispatcher.rs#L671-L674
we could instead do something like this:
```rust
        if let Some(dispatch) = self.0.take() {
            let prev = CURRENT_STATE.try_with(|state| {
                state.default.borrow_mut().replace(dispatch);
            });
            drop(prev);
        }
```
this way, we explicitly drop the `Dispatch` _outside_ of `borrow_mut`, and if this triggers the `Subscriber` to drop because this `Dispatch` was the last reference to it, it will have already been unset. I think dropping the dispatcher outside of the thread-local access is _probably_ the right thing to do regardless.

**Comment by d-e-s-o** [comment]
Good suggestion. Solves the issue for me. I'll open a pull request if you don't mind.
